CREATE TABLE IF NOT EXISTS "mentioned_tweets" (
	"id" text PRIMARY KEY NOT NULL,
	"text" text NOT NULL,
	"author" text NOT NULL,
	"author_username" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"likes" integer DEFAULT 0 NOT NULL,
	"retweets" integer DEFAULT 0 NOT NULL,
	"author_followers" integer DEFAULT 0 NOT NULL,
	"author_verified" boolean DEFAULT false NOT NULL,
	"processed" boolean DEFAULT false NOT NULL,
	"processed_at" timestamp with time zone,
	"created_timestamp" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"response_tweet_id" text,
	"response_text" text,
	"response_error" text,
	"search_query" text NOT NULL,
	"mention_type" text NOT NULL,
	"engagement_score" real,
	"sentiment_score" real,
	"priority_score" real,
	"retry_count" integer DEFAULT 0 NOT NULL,
	"last_retry_at" timestamp with time zone,
	"deleted_at" timestamp with time zone,
	"sentiment_positive" real,
	"sentiment_negative" real,
	"sentiment_helpful" real,
	"sentiment_sarcastic" real,
	"ducky_reply" text,
	"content" text
);
